### ISSUE TITLE
Add PATCH verb

### ISSUE THREAD

**Issue by jacobrheath** [arkadiyt/ssrf_filter#37]
Any interest in adding additional verbs to the verb list? It would be nice to utilize the PATCH verb. If you agree, I would be happy to open a PR to contribute. Thanks!

**Comment by arkadiyt** [comment]
Sure, happy to accept a PR for the patch verb

**Comment by jacobrheath** [comment]
Great, @arkadiyt! I submitted a PR, although, I am not the most proficient ruby programmer. One of my tests seems to be failing for ruby 2.0 and I don't know the best way to fix it. Any help on merging that PR would be great. Thanks!

**Comment by jacobrheath** [comment]
closed by #38
