### ISSUE TITLE
Drop support for old ruby versions

### ISSUE THREAD

**Issue by sandstrom** [arkadiyt/ssrf_filter#40]
Thanks for an awesome gem! 💎 

At some point it'll probably make sense to drop support for old ruby versions, to make this easier to maintain.

Just wanted to raise the issue, feel free to close this right away if you don't think the time is right to drop any of the older ones just yet.

**Comment by arkadiyt** [comment]
@sandstrom is this causing issues for you or your org somehow?

**Comment by sandstrom** [comment]
No, not at all 😄

Sometimes I suggest things that make gems easier to maintain (e.g. reducing their scope, suggest supporting outdated versions), purely because I like the gem and want to see it maintained over time. That's the reason I ask.

But just wanted to raise the question, totally understand if you want to support older versions for a while longer.
