### ISSUE TITLE
Create a new tag for the latest changes that include HEAD requests

### ISSUE THREAD

**Issue by chrisballen** [arkadiyt/ssrf_filter#45]
Hello, just wondering when you all will create a new tag that will include the latest changes merged which include supporting HEAD requests.  We would like to include that in our project as right now we are referencing a specific commit.  Thank you.

**Comment by arkadiyt** [comment]
Thanks for flagging @chrisballen - this should be pushed now

**Comment by chrisballen** [comment]
@arkadiyt so the latest changes are in master, but will you not create a new tag `1.0.8`?  I am seeing the last tag was created in 2019.  We would like to reference a specific version not master. 
![image](https://user-images.githubusercontent.com/705079/182980762-1659f894-0a73-47d0-b18e-4b58df25d486.png)

**Comment by chrisballen** [comment]
Never mind @arkadiyt.  I made a mistake and we are still able to pull the correct version.  Thanks for making the changes.

**Comment by arkadiyt** [comment]
Ah yeah I published to rubygems but forgot to make a github release - that's fixed now
