### ISSUE TITLE
When try to get body I have error NoMethodError: undefined method `closed?' for nil:NilClass

### ISSUE THREAD

**Issue by DmytroKondratiuk** [arkadiyt/ssrf_filter#58]
In version "1.1.0" when try to get body I have error. For example:

     photo_url = any photo url
     SsrfFilter.get(photo_url).body

Error:

    NoMethodError: undefined method `closed?' for nil:NilClass
    raise IOError, 'attempt to read body out of block' if @socket.closed?

**Comment by nickcoyne** [comment]
I get this same error with Carrierwave trying to set a remote url for an image.

**Comment by arkadiyt** [comment]
Can you share a sample url to reproduce the issue?

**Comment by nickcoyne** [comment]
I think my issue is caused by https://github.com/arkadiyt/ssrf_filter/issues/56

**Comment by DmitriyKondratyuk** [comment]
For example
photo_url = 'https://ssl.gstatic.com/ui/v1/icons/mail/rfr/logo_gmail_lockup_dark_2x_r5.png'

<img width="915" alt="Screenshot 2022-09-16 at 09 42 02" src="https://user-images.githubusercontent.com/13381209/190573452-aaf5b9de-ee17-4019-942c-3a669adf840a.png">

In version 1.0.8 when we try get a photo `SsrfFilter.get(photo_url)` answer:

    #<Net::HTTPOK 200 OK readbody=true>

In version 1.1.0 when we try get a photo `SsrfFilter.get(photo_url)` answer:

    #<Net::HTTPOK 200 OK readbody=false>

**Comment by vinc** [comment]
Same issue for a private project that was solved by downgrading to 1.0.8

**Comment by basex** [comment]
I confirm the fix by https://github.com/arkadiyt/ssrf_filter/pull/60
