### ISSUE TITLE
1.1.1 version breaks Resolv gem IPv4

### ISSUE THREAD

**Issue by lorrocha** [arkadiyt/ssrf_filter#61]
The monkeypatch for the Resolv gem is actually breaking the regex class for IPv4.

https://github.com/ruby/resolv/blob/993a1a374fcb2a91b9d26a2215ddbb116db43788/lib/resolv.rb#L2349

As far as I can tell, it's due to the code found here:

```
        if (0..255) === (a = $1.to_i) &&
           (0..255) === (b = $2.to_i) &&
           (0..255) === (c = $3.to_i) &&
           (0..255) === (d = $4.to_i)
```

It expects global variables $1 to $4 to be set, with values matching each of the ipv4 groups. The overriding === method does not set these global variables in the monkey patched implementation, so one ends up with an IPv4 object with address 0.0.0.0, because the globals are nil and nil.to_i is 0.

An example of an IPv4 dns that breaks is: `Resolv.getname('167.89.116.35')`

This works before the Resolv patch is applied, but breaks once Resolve has been patched.

**Comment by arkadiyt** [comment]
@lorrocha sorry on the very long delay here, this should be fixed on main and I'll be doing a release soon
