### ISSUE TITLE
Weird timeout in specific domain

### ISSUE THREAD

**Issue by marcosmighty** [arkadiyt/ssrf_filter#65]
We're having some trouble timing out in the .get method from the gem in a specific domain: https://www.npr.org/. Every request from this one is timing out in the get method. 
If you guys already got some issue like that with other domains it'd be great for us to know some kind of worakround.

version:
`'ssrf_filter', '~> 1.0'`

**Comment by arkadiyt** [comment]
This doesn't seem specific to ssrf_filter, even doing a plain http get has the same behavior:
```
Net::HTTP.get(URI('https://www.npr.org/'))
```

They might be doing some blocking on their side
