### ISSUE TITLE
EOFError (end of file reached) for some sites

### ISSUE THREAD

**Issue by gmartinimighty** [arkadiyt/ssrf_filter#67]
I'm getting the "EOFError (end of file reached)" for some sites, for example 
- https://www.pocket-lint.com/
- https://www.androidpolice.com/google-messages-leapfrog-apple-satellite-connectivity/

Doing some research on the internet I found out this issue is caused by the user agent having the "ruby" word on the user agent.

Links:
https://stackoverflow.com/questions/50272370/rails-http-request-raises-eoferror-end-of-file-reached-after-some-time
https://github.com/jnunemaker/httparty/issues/594

I tested the potential fix locally and it works well for me. I will create a PR with it.

**Comment by arkadiyt** [comment]
Closing as per https://github.com/arkadiyt/ssrf_filter/pull/68#issuecomment-1703030804
